login: &common
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 
  host: localhost
  port: 5433
  database: amp
  min_messages: warning # silence the NOTICE: messages from postgres


development:
  <<: *common

qa:
  <<: *common
  username: amts
  host: qa-ampapp1.collective-media.net

newqa:
  <<: *common
  username: amp
  password: amp0986N
  host: 10.128.170.229

newstg:
  <<: *common
  username: amp
  password: amp0986N
  host: 10.128.171.234

stg:
  <<: *common
  username: amts
  host: stg-ampdb1.collective-media.net

production:
  <<: *common
  username: amts
  host: ampdb1.collective-media.net

test:
  <<: *common
  username: amp
  password: 
  database: amp_test
